### PR TITLE
API

### PR DESCRIPTION
**Pull request by youben11**
This PR proposes an API for the PSI libraries. I thought that a general purpose library should only let the user inputs its set, the protocol he wanna use and information about the remote server, the rest should be transparent, everything should be taken care of in the `client_intersect` function. On the server side, each protocol should have its own implementation, but we provide a constructor function `create_server` that take the server set, the protocol we wanna use and information about how to listen to queries, then the server should be started with `server.start()`.

An example of how to use this API:

#### Server

```python
import psi

elements = [1, 2, 3, 4, 5, 6]
server = psi.create_server(elements, ip='x.x.x.x', port=n)
server.start()
```

#### Client

```python
import psi

elements = [2, 5, 10,]
intersection = psi.client_intersect(elements, ip='x.x.x.x', port=n)
```

### CODE REVIEW

**Comment by MichaelHoeh** [comment]
Based on the discussion in Slack I propose a slightly different setup, abstracting away specifics of transport layer as much as possible.

I refactored the main method in the `test.py` file, to outline my idea of the API. This is still rough, but this is how I would see it:

`# Server
def server_setup():
    bf = server.setup_bf(private_key, X)
    f = BytesIO()
    utils.save_bf(bf, f)
    size = f.tell()

def server_psi_step2():
    B = server.sign_batch(private_key, A)


# Client
def client_setup():
    private_key = generate_private_key(m, e)
    public_key = RSA.construct((private_key.n, private_key.e))
    random_factors = client.generate_random_factors(public_key)

def client_psi_step1():
    A = client.blind_batch(Y, random_factors, public_key.n)

def client_psi_step3():
    X_Y = client.intersect(Y, B, random_factors, bf, public_key)
`

Each PSI protocol has multiple steps, and for an outsider looking into the code, this way it would be quick to understand how steps mentioned in the docs are reflected in the code. As an engineer, I should pretty much just need to know "there are two parties that send around data in multiple steps/rounds", and then find the corresponding implementation in the code. As an engineer, I can then go ahead and put e.g. a Flask API endpoint around it, like:

`
from flask import Flask
app = Flask(__name__)

@app.route('/server_step2')
def run_step2():
    server_psi_step2():
`

Ideally, we would also have:
- a general object that we pass around, e.g. a python dictionary that is easy to serialize to JSON. This way we would not have to pass `intersect(Y, B, random_factors, bf, public_key)` like you do it now, but rather `intersect(data_object)`, where data_object = {Y: ..., B:, ..., ...} is a dict/JSON that holds the individual values. This way the engineer just needs to know that there is one object he has to serialize and send around, and this object contains all he needs
- a general `data_loader` class or something like this, which could implement different `load_data()` methods. We could implement a simple `load_data()` method for reading data from disk, and then the engineer could just implement another such method doing SQL, or anything else.

My general idea with the API would be: easy for an engineer to understand without digging in the details, and with clear hints where he can get data in and out, and how he could integrate it into his system. To achieve this, we can implement a basic setup with web API/datastorage AROUND our library, but I would not make this the key part of the library. What do you think?

**Comment by MichaelHoeh** [comment]
as this suggestion above is quite specific to the protocol, we could also do something try to take an intermediate step, i.e. try to abstract specific commands into easy building blocks, out of which we could compose multiple PSI logics, maybe similar to:


```python
def prep_bloomfilter():
   bf = server.setup_bf(private_key, X)
    f = BytesIO()
    utils.save_bf(bf, f)
    size = f.tell()

def server_setup_psi1():
    prep_bloomfilter() 
```

and then we could have `psi1` being one protocol, `psi2` another, potentially re-using the same building blocks. And then doing the individual `psi1_step1()` and so on methods would be straight forward.

**Comment by MichaelHoeh** [comment]
Regarding methods / endpoints design for different versions, that could be of different length, maybe something like this makes sense:

### low level
```python
def v1_step1(): pass
def v1_step2(): pass
def v2_step1(): pass
def v2_step2(): pass
def v2_step3(): pass
```

### high level
```python
def run_v1(): 
     v1_step1()
     v1_step2()

def run_v2(): 
     v2_step1()
     v2_step2()
     v2_step3()
```

And then there could be REST endpoints for `run_v1` and `run_v2`. If the engineer implements our high level API, then he just needs to go to different endpoint, and potentially adjust data structures he feeds into the endpoint

**Comment by youben11** [comment]
The API should now looks like this.

#### Server
```python
import psi

elements = [1, 2, 3, 4, 5, 6]
server = psi.create_server(elements)
# expose server methods then
server.step1
server.step2
...
```

#### Client

```python
import psi

elements = [2, 5, 10,]

# high level
intersection = psi.client_intersect(elements, base_url="https://psi.openmined.org")

# low level
client = psi.create_client(elements, base_url="https://psi.openmined.org")
client.step1()
client.step2()
...
```

The API here assumes the usage of REST, if we really want to remove this, then we can make the step function return a dictionary to be sent instead of sending it. A higher level function like `client_intersect` would then be impossible without specifying the mean of communication (e.g. REST)

Something I'm not sure about is either the server methods should be endpoints that process client's requests directly? Like should we implement them as REST endpoints from the beginning?

**Comment by youben11** [comment]
Moving to a lower level API

**Pull request closed without merging**
